# Generated by Django 5.2.15 on 2026-09-02

import uuid
from itertools import islice

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_page_documents(apps, schema_editor):
    Document = apps.get_model("db", "Document")
    DocumentProject = apps.get_model("db", "DocumentProject")
    Page = apps.get_model("db", "Page")
    ProjectPage = apps.get_model("db", "ProjectPage")

    pages = Page._base_manager.iterator(chunk_size=1000)
    while batch := list(islice(pages, 1000)):
        Document._base_manager.bulk_create(
            [
                Document(
                    id=page.id,
                    kind="page",
                    workspace_id=page.workspace_id,
                    owned_by_id=page.owned_by_id,
                    name=page.name,
                    access=page.access,
                    archived_at=page.archived_at,
                    is_locked=page.is_locked,
                    sort_order=page.sort_order,
                    created_at=page.created_at,
                    updated_at=page.updated_at,
                    created_by_id=page.created_by_id,
                    updated_by_id=page.updated_by_id,
                    deleted_at=page.deleted_at,
                )
                for page in batch
            ],
            batch_size=1000,
            ignore_conflicts=True,
        )

    project_pages = ProjectPage._base_manager.iterator(chunk_size=1000)
    while batch := list(islice(project_pages, 1000)):
        DocumentProject._base_manager.bulk_create(
            [
                DocumentProject(
                    id=link.id,
                    document_id=link.page_id,
                    project_id=link.project_id,
                    workspace_id=link.workspace_id,
                    created_at=link.created_at,
                    updated_at=link.updated_at,
                    created_by_id=link.created_by_id,
                    updated_by_id=link.updated_by_id,
                    deleted_at=link.deleted_at,
                )
                for link in batch
            ],
            batch_size=1000,
            ignore_conflicts=True,
        )


class Migration(migrations.Migration):
    dependencies = [("db", "0122_alter_draftissue_assignees_alter_issue_assignees_and_more")]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("kind", models.CharField(choices=[("page", "Page"), ("work-map", "Work map")], max_length=8)),
                ("name", models.TextField(blank=True)),
                ("access", models.PositiveSmallIntegerField(choices=[(0, "Public"), (1, "Private")], default=0)),
                ("archived_at", models.DateField(null=True)),
                ("is_locked", models.BooleanField(default=False)),
                ("sort_order", models.FloatField(default=65535)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "owned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="db.workspace",
                    ),
                ),
            ],
            options={"db_table": "documents", "ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="WorkMap",
            fields=[
                (
                    "document",
                    models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="work_map",
                        serialize=False,
                        to="db.document",
                    ),
                ),
                ("scene_binary", models.BinaryField(default=bytes)),
                ("generation", models.PositiveBigIntegerField(default=0)),
            ],
            options={"db_table": "work_maps"},
        ),
        migrations.CreateModel(
            name="DocumentProject",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="document_projects", to="db.document"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="project_documents", to="db.project"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="document_projects", to="db.workspace"
                    ),
                ),
            ],
            options={"db_table": "document_projects", "ordering": ("-created_at",)},
        ),
        migrations.AddField(
            model_name="document",
            name="projects",
            field=models.ManyToManyField(related_name="documents", through="db.DocumentProject", to="db.project"),
        ),
        migrations.CreateModel(
            name="WorkMapBinding",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("node_key", models.UUIDField(unique=True)),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("work-item", "Work item"),
                            ("cycle", "Cycle"),
                            ("module", "Module"),
                            ("project-view", "Project view"),
                            ("page", "Page"),
                            ("intake-item", "Intake item"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_id", models.UUIDField()),
                ("revision", models.PositiveBigIntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "work_map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="bindings", to="db.workmap"
                    ),
                ),
            ],
            options={"db_table": "work_map_bindings", "ordering": ("created_at",)},
        ),
        migrations.AddConstraint(
            model_name="documentproject",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("document", "project"),
                name="document_project_unique_active_link",
            ),
        ),
        migrations.AddConstraint(
            model_name="workmapbinding",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("work_map", "source_kind", "source_id"),
                name="work_map_binding_unique_active_source",
            ),
        ),
        migrations.RunPython(backfill_page_documents, migrations.RunPython.noop),
    ]
