# Generated by Django 5.2.15 on 2026-09-02

import uuid
from itertools import islice

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone

import plane.db.models.page


PAGE_FIELDS = (
    "id",
    "workspace_id",
    "owned_by_id",
    "name",
    "access",
    "archived_at",
    "is_locked",
    "sort_order",
    "created_at",
    "updated_at",
    "created_by_id",
    "updated_by_id",
    "deleted_at",
)
PROJECT_FIELDS = (
    "id",
    "page_id",
    "project_id",
    "workspace_id",
    "created_at",
    "updated_at",
    "created_by_id",
    "updated_by_id",
    "deleted_at",
)
VERSION_FIELDS = (
    "id",
    "page_id",
    "workspace_id",
    "last_saved_at",
    "owned_by_id",
    "created_at",
    "updated_at",
    "created_by_id",
    "updated_by_id",
    "deleted_at",
)


def backfill_page_document_owners(apps, schema_editor):
    Document = apps.get_model("db", "Document")
    DocumentProject = apps.get_model("db", "DocumentProject")
    DocumentVersion = apps.get_model("db", "DocumentVersion")
    Page = apps.get_model("db", "Page")
    PageVersion = apps.get_model("db", "PageVersion")
    ProjectPage = apps.get_model("db", "ProjectPage")

    pages = Page._base_manager.iterator(chunk_size=1000)
    while batch := list(islice(pages, 1000)):
        Document._base_manager.bulk_create(
            [
                Document(
                    id=page.id,
                    kind="page",
                    workspace_id=page.workspace_id,
                    owned_by_id=page.owned_by_id,
                    name=page.name,
                    access=page.access,
                    archived_at=page.archived_at,
                    is_locked=page.is_locked,
                    sort_order=page.sort_order,
                )
                for page in batch
            ],
            batch_size=1000,
            ignore_conflicts=True,
        )
        for page in batch:
            Document._base_manager.filter(id=page.id, kind="page").update(
                workspace_id=page.workspace_id,
                owned_by_id=page.owned_by_id,
                name=page.name,
                access=page.access,
                archived_at=page.archived_at,
                is_locked=page.is_locked,
                sort_order=page.sort_order,
                created_at=page.created_at,
                updated_at=page.updated_at,
                created_by_id=page.created_by_id,
                updated_by_id=page.updated_by_id,
                deleted_at=page.deleted_at,
            )

    project_pages = ProjectPage._base_manager.iterator(chunk_size=1000)
    while batch := list(islice(project_pages, 1000)):
        DocumentProject._base_manager.bulk_create(
            [
                DocumentProject(
                    id=link.id,
                    document_id=link.page_id,
                    project_id=link.project_id,
                    workspace_id=link.workspace_id,
                )
                for link in batch
            ],
            batch_size=1000,
            ignore_conflicts=True,
        )
        for link in batch:
            DocumentProject._base_manager.filter(
                id=link.id,
                document_id=link.page_id,
                project_id=link.project_id,
                workspace_id=link.workspace_id,
            ).update(
                created_at=link.created_at,
                updated_at=link.updated_at,
                created_by_id=link.created_by_id,
                updated_by_id=link.updated_by_id,
                deleted_at=link.deleted_at,
            )

    page_versions = PageVersion._base_manager.iterator(chunk_size=1000)
    while batch := list(islice(page_versions, 1000)):
        DocumentVersion._base_manager.bulk_create(
            [
                DocumentVersion(
                    id=version.id,
                    document_id=version.page_id,
                    workspace_id=version.workspace_id,
                    last_saved_at=version.last_saved_at,
                    owned_by_id=version.owned_by_id,
                )
                for version in batch
            ],
            batch_size=1000,
            ignore_conflicts=True,
        )
        for version in batch:
            DocumentVersion._base_manager.filter(
                id=version.id,
                document_id=version.page_id,
                workspace_id=version.workspace_id,
                owned_by_id=version.owned_by_id,
            ).update(
                last_saved_at=version.last_saved_at,
                created_at=version.created_at,
                updated_at=version.updated_at,
                created_by_id=version.created_by_id,
                updated_by_id=version.updated_by_id,
                deleted_at=version.deleted_at,
            )


def verify_document_parity(apps, schema_editor):
    quoted_page_fields = ", ".join(f'p."{field}"' for field in PAGE_FIELDS)
    quoted_document_fields = ", ".join(f'd."{field if field != "id" else "id"}"' for field in PAGE_FIELDS)
    quoted_project_fields = ", ".join(f'pp."{field}"' for field in PROJECT_FIELDS)
    quoted_document_project_fields = ", ".join(
        f'dp."{field if field != "page_id" else "document_id"}"' for field in PROJECT_FIELDS
    )
    quoted_page_version_fields = ", ".join(f'pv."{field}"' for field in VERSION_FIELDS)
    quoted_document_version_fields = ", ".join(
        f'dv."{field if field != "page_id" else "document_id"}"' for field in VERSION_FIELDS
    )
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f"""
            SELECT COUNT(*)
            FROM (
                SELECT {quoted_page_fields} FROM pages p
                EXCEPT
                SELECT {quoted_document_fields} FROM documents d WHERE d.kind = 'page'
            ) differences
            """
        )
        page_differences = cursor.fetchone()[0]
        cursor.execute(
            f"""
            SELECT COUNT(*)
            FROM (
                SELECT {quoted_document_fields} FROM documents d WHERE d.kind = 'page'
                EXCEPT
                SELECT {quoted_page_fields} FROM pages p
            ) differences
            """
        )
        document_differences = cursor.fetchone()[0]
        cursor.execute(
            f"""
            SELECT COUNT(*)
            FROM (
                SELECT {quoted_project_fields} FROM project_pages pp
                EXCEPT
                SELECT {quoted_document_project_fields}
                FROM document_projects dp
                JOIN documents d ON d.id = dp.document_id
                WHERE d.kind = 'page'
            ) differences
            """
        )
        project_page_differences = cursor.fetchone()[0]
        cursor.execute(
            f"""
            SELECT COUNT(*)
            FROM (
                SELECT {quoted_document_project_fields}
                FROM document_projects dp
                JOIN documents d ON d.id = dp.document_id
                WHERE d.kind = 'page'
                EXCEPT
                SELECT {quoted_project_fields} FROM project_pages pp
            ) differences
            """
        )
        document_project_differences = cursor.fetchone()[0]
        cursor.execute(
            f"""
            SELECT COUNT(*)
            FROM (
                SELECT {quoted_page_version_fields} FROM page_versions pv
                EXCEPT
                SELECT {quoted_document_version_fields}
                FROM document_versions dv
                JOIN documents d ON d.id = dv.document_id
                WHERE d.kind = 'page'
            ) differences
            """
        )
        page_version_differences = cursor.fetchone()[0]
        cursor.execute(
            f"""
            SELECT COUNT(*)
            FROM (
                SELECT {quoted_document_version_fields}
                FROM document_versions dv
                JOIN documents d ON d.id = dv.document_id
                WHERE d.kind = 'page'
                EXCEPT
                SELECT {quoted_page_version_fields} FROM page_versions pv
            ) differences
            """
        )
        document_version_differences = cursor.fetchone()[0]

    if any(
        (
            page_differences,
            document_differences,
            project_page_differences,
            document_project_differences,
            page_version_differences,
            document_version_differences,
        )
    ):
        raise RuntimeError("Page to Document cutover blocked by lifecycle, version, or project-association drift")


def restore_legacy_page_storage(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE pages p
            SET workspace_id = d.workspace_id,
                owned_by_id = d.owned_by_id,
                name = d.name,
                access = d.access,
                archived_at = d.archived_at,
                is_locked = d.is_locked,
                sort_order = d.sort_order,
                created_at = d.created_at,
                updated_at = d.updated_at,
                created_by_id = d.created_by_id,
                updated_by_id = d.updated_by_id,
                deleted_at = d.deleted_at
            FROM documents d
            WHERE d.id = p.id AND d.kind = 'page'
            """
        )
        cursor.execute(
            """
            INSERT INTO project_pages (
                id, page_id, project_id, workspace_id, created_at, updated_at,
                created_by_id, updated_by_id, deleted_at
            )
            SELECT
                dp.id, dp.document_id, dp.project_id, dp.workspace_id,
                dp.created_at, dp.updated_at, dp.created_by_id,
                dp.updated_by_id, dp.deleted_at
            FROM document_projects dp
            JOIN documents d ON d.id = dp.document_id
            WHERE d.kind = 'page'
            ON CONFLICT (id) DO UPDATE SET
                page_id = EXCLUDED.page_id,
                project_id = EXCLUDED.project_id,
                workspace_id = EXCLUDED.workspace_id,
                created_at = EXCLUDED.created_at,
                updated_at = EXCLUDED.updated_at,
                created_by_id = EXCLUDED.created_by_id,
                updated_by_id = EXCLUDED.updated_by_id,
                deleted_at = EXCLUDED.deleted_at
            """
        )
        cursor.execute(
            """
            DELETE FROM project_pages pp
            USING pages p
            WHERE pp.page_id = p.id
              AND NOT EXISTS (
                  SELECT 1 FROM document_projects dp WHERE dp.id = pp.id
              )
            """
        )
        cursor.execute(
            """
            UPDATE page_versions pv
            SET page_id = dv.document_id,
                workspace_id = dv.workspace_id,
                last_saved_at = dv.last_saved_at,
                owned_by_id = dv.owned_by_id,
                created_at = dv.created_at,
                updated_at = dv.updated_at,
                created_by_id = dv.created_by_id,
                updated_by_id = dv.updated_by_id,
                deleted_at = dv.deleted_at
            FROM document_versions dv
            WHERE dv.id = pv.id
            """
        )


def finalize_legacy_page_storage(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            ALTER TABLE pages
                ALTER COLUMN workspace_id SET NOT NULL,
                ALTER COLUMN owned_by_id SET NOT NULL,
                ALTER COLUMN name SET NOT NULL,
                ALTER COLUMN access SET NOT NULL,
                ALTER COLUMN is_locked SET NOT NULL,
                ALTER COLUMN sort_order SET NOT NULL,
                ALTER COLUMN created_at SET NOT NULL,
                ALTER COLUMN updated_at SET NOT NULL;
            ALTER TABLE pages
                ADD CONSTRAINT pages_access_check CHECK (access >= 0),
                ADD CONSTRAINT pages_workspace_id_c6c51010_fk_workspaces_id
                    FOREIGN KEY (workspace_id) REFERENCES workspaces(id) DEFERRABLE INITIALLY DEFERRED,
                ADD CONSTRAINT pages_owned_by_id_bf50485f_fk_users_id
                    FOREIGN KEY (owned_by_id) REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED,
                ADD CONSTRAINT pages_created_by_id_d109a675_fk_users_id
                    FOREIGN KEY (created_by_id) REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED,
                ADD CONSTRAINT pages_updated_by_id_6c42de3e_fk_users_id
                    FOREIGN KEY (updated_by_id) REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED;
            CREATE INDEX pages_workspace_id_c6c51010 ON pages (workspace_id);
            CREATE INDEX pages_owned_by_id_bf50485f ON pages (owned_by_id);
            CREATE INDEX pages_created_by_id_d109a675 ON pages (created_by_id);
            CREATE INDEX pages_updated_by_id_6c42de3e ON pages (updated_by_id);

            ALTER TABLE page_versions
                ALTER COLUMN workspace_id SET NOT NULL,
                ALTER COLUMN page_id SET NOT NULL,
                ALTER COLUMN last_saved_at SET NOT NULL,
                ALTER COLUMN owned_by_id SET NOT NULL,
                ALTER COLUMN created_at SET NOT NULL,
                ALTER COLUMN updated_at SET NOT NULL;
            ALTER TABLE page_versions
                ADD CONSTRAINT page_versions_workspace_id_8330a200_fk_workspaces_id
                    FOREIGN KEY (workspace_id) REFERENCES workspaces(id) DEFERRABLE INITIALLY DEFERRED,
                ADD CONSTRAINT page_versions_owned_by_id_6d9143db_fk_users_id
                    FOREIGN KEY (owned_by_id) REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED,
                ADD CONSTRAINT page_versions_page_id_c46471da_fk_pages_id
                    FOREIGN KEY (page_id) REFERENCES pages(id) DEFERRABLE INITIALLY DEFERRED,
                ADD CONSTRAINT page_versions_created_by_id_d660b13b_fk_users_id
                    FOREIGN KEY (created_by_id) REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED,
                ADD CONSTRAINT page_versions_updated_by_id_72d5e579_fk_users_id
                    FOREIGN KEY (updated_by_id) REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED;
            CREATE INDEX page_versions_workspace_id_8330a200 ON page_versions (workspace_id);
            CREATE INDEX page_versions_owned_by_id_6d9143db ON page_versions (owned_by_id);
            CREATE INDEX page_versions_page_id_c46471da ON page_versions (page_id);
            CREATE INDEX page_versions_created_by_id_d660b13b ON page_versions (created_by_id);
            CREATE INDEX page_versions_updated_by_id_72d5e579 ON page_versions (updated_by_id);
            """
        )


class Migration(migrations.Migration):
    dependencies = [("db", "0123_document_work_map")]

    operations = [
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("last_saved_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_versions",
                        to="db.document",
                    ),
                ),
                (
                    "owned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_versions",
                        to="db.workspace",
                    ),
                ),
            ],
            options={"db_table": "document_versions", "ordering": ("-created_at",)},
        ),
        migrations.RunPython(backfill_page_document_owners, finalize_legacy_page_storage),
        migrations.RunPython(verify_document_parity, restore_legacy_page_storage),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE pages
                        ADD CONSTRAINT pages_document_parent_fk
                        FOREIGN KEY (id) REFERENCES documents(id)
                        DEFERRABLE INITIALLY DEFERRED;
                    ALTER TABLE page_versions
                        ADD CONSTRAINT page_versions_document_version_parent_fk
                        FOREIGN KEY (id) REFERENCES document_versions(id)
                        DEFERRABLE INITIALLY DEFERRED;

                    ALTER TABLE page_versions
                        DROP COLUMN workspace_id,
                        DROP COLUMN page_id,
                        DROP COLUMN last_saved_at,
                        DROP COLUMN owned_by_id,
                        DROP COLUMN created_at,
                        DROP COLUMN updated_at,
                        DROP COLUMN created_by_id,
                        DROP COLUMN updated_by_id,
                        DROP COLUMN deleted_at;
                    ALTER TABLE pages
                        DROP COLUMN workspace_id,
                        DROP COLUMN owned_by_id,
                        DROP COLUMN name,
                        DROP COLUMN access,
                        DROP COLUMN archived_at,
                        DROP COLUMN is_locked,
                        DROP COLUMN sort_order,
                        DROP COLUMN created_at,
                        DROP COLUMN updated_at,
                        DROP COLUMN created_by_id,
                        DROP COLUMN updated_by_id,
                        DROP COLUMN deleted_at;
                    DROP TABLE project_pages;
                    """,
                    reverse_sql="""
                    CREATE TABLE project_pages (
                        created_at timestamp with time zone NOT NULL,
                        updated_at timestamp with time zone NOT NULL,
                        id uuid PRIMARY KEY,
                        created_by_id uuid NULL,
                        page_id uuid NOT NULL,
                        project_id uuid NOT NULL,
                        updated_by_id uuid NULL,
                        workspace_id uuid NOT NULL,
                        deleted_at timestamp with time zone NULL,
                        CONSTRAINT project_pages_created_by_id_b9d02062_fk_users_id
                            FOREIGN KEY (created_by_id) REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED,
                        CONSTRAINT project_pages_page_id_a0f54439_fk_pages_id
                            FOREIGN KEY (page_id) REFERENCES pages(id) DEFERRABLE INITIALLY DEFERRED,
                        CONSTRAINT project_pages_project_id_376ba35a_fk_projects_id
                            FOREIGN KEY (project_id) REFERENCES projects(id) DEFERRABLE INITIALLY DEFERRED,
                        CONSTRAINT project_pages_updated_by_id_b80bf0f4_fk_users_id
                            FOREIGN KEY (updated_by_id) REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED,
                        CONSTRAINT project_pages_workspace_id_13ed9e73_fk_workspaces_id
                            FOREIGN KEY (workspace_id) REFERENCES workspaces(id) DEFERRABLE INITIALLY DEFERRED,
                        CONSTRAINT project_pages_project_id_page_id_deleted_at_7c80a40c_uniq
                            UNIQUE (project_id, page_id, deleted_at)
                    );
                    CREATE UNIQUE INDEX project_page_unique_project_page_when_deleted_at_null
                        ON project_pages (project_id, page_id) WHERE deleted_at IS NULL;
                    CREATE INDEX project_pages_created_by_id_b9d02062 ON project_pages (created_by_id);
                    CREATE INDEX project_pages_page_id_a0f54439 ON project_pages (page_id);
                    CREATE INDEX project_pages_project_id_376ba35a ON project_pages (project_id);
                    CREATE INDEX project_pages_updated_by_id_b80bf0f4 ON project_pages (updated_by_id);
                    CREATE INDEX project_pages_workspace_id_13ed9e73 ON project_pages (workspace_id);

                    ALTER TABLE pages DROP CONSTRAINT pages_document_parent_fk;
                    ALTER TABLE pages
                        ADD COLUMN workspace_id uuid NULL,
                        ADD COLUMN owned_by_id uuid NULL,
                        ADD COLUMN name text NULL,
                        ADD COLUMN access smallint NULL,
                        ADD COLUMN archived_at date NULL,
                        ADD COLUMN is_locked boolean NULL,
                        ADD COLUMN sort_order double precision NULL,
                        ADD COLUMN created_at timestamp with time zone NULL,
                        ADD COLUMN updated_at timestamp with time zone NULL,
                        ADD COLUMN created_by_id uuid NULL,
                        ADD COLUMN updated_by_id uuid NULL,
                        ADD COLUMN deleted_at timestamp with time zone NULL;

                    ALTER TABLE page_versions
                        DROP CONSTRAINT page_versions_document_version_parent_fk;
                    ALTER TABLE page_versions
                        ADD COLUMN workspace_id uuid NULL,
                        ADD COLUMN page_id uuid NULL,
                        ADD COLUMN last_saved_at timestamp with time zone NULL,
                        ADD COLUMN owned_by_id uuid NULL,
                        ADD COLUMN created_at timestamp with time zone NULL,
                        ADD COLUMN updated_at timestamp with time zone NULL,
                        ADD COLUMN created_by_id uuid NULL,
                        ADD COLUMN updated_by_id uuid NULL,
                        ADD COLUMN deleted_at timestamp with time zone NULL;
                    """,
                )
            ],
            state_operations=[
                migrations.DeleteModel(name="ProjectPage"),
                migrations.DeleteModel(name="PageVersion"),
                migrations.DeleteModel(name="Page"),
                migrations.CreateModel(
                    name="Page",
                    fields=[
                        (
                            "document_ptr",
                            models.OneToOneField(
                                db_column="id",
                                on_delete=django.db.models.deletion.CASCADE,
                                parent_link=True,
                                primary_key=True,
                                related_name="page",
                                serialize=False,
                                to="db.document",
                            ),
                        ),
                        ("description_json", models.JSONField(blank=True, default=dict)),
                        ("description_binary", models.BinaryField(null=True)),
                        ("description_html", models.TextField(blank=True, default="<p></p>")),
                        ("description_stripped", models.TextField(blank=True, null=True)),
                        ("color", models.CharField(blank=True, max_length=255)),
                        ("view_props", models.JSONField(default=plane.db.models.page.get_view_props)),
                        ("logo_props", models.JSONField(default=dict)),
                        ("is_global", models.BooleanField(default=False)),
                        ("moved_to_page", models.UUIDField(blank=True, null=True)),
                        ("moved_to_project", models.UUIDField(blank=True, null=True)),
                        ("external_id", models.CharField(blank=True, max_length=255, null=True)),
                        ("external_source", models.CharField(blank=True, max_length=255, null=True)),
                        (
                            "labels",
                            models.ManyToManyField(
                                blank=True,
                                related_name="pages",
                                through="db.PageLabel",
                                to="db.label",
                            ),
                        ),
                        (
                            "parent",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="child_page",
                                to="db.page",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Page",
                        "verbose_name_plural": "Pages",
                        "db_table": "pages",
                        "ordering": ("-created_at",),
                    },
                    bases=("db.document",),
                ),
                migrations.CreateModel(
                    name="PageVersion",
                    fields=[
                        (
                            "document_version_ptr",
                            models.OneToOneField(
                                db_column="id",
                                on_delete=django.db.models.deletion.CASCADE,
                                parent_link=True,
                                primary_key=True,
                                related_name="page_version",
                                serialize=False,
                                to="db.documentversion",
                            ),
                        ),
                        ("description_binary", models.BinaryField(null=True)),
                        ("description_html", models.TextField(blank=True, default="<p></p>")),
                        ("description_stripped", models.TextField(blank=True, null=True)),
                        ("description_json", models.JSONField(blank=True, default=dict)),
                        ("sub_pages_data", models.JSONField(blank=True, default=dict)),
                    ],
                    options={
                        "verbose_name": "Page Version",
                        "verbose_name_plural": "Page Versions",
                        "db_table": "page_versions",
                        "ordering": ("-created_at",),
                    },
                    bases=("db.documentversion",),
                ),
            ],
        ),
    ]
