# Generated by Django 5.2.15 on 2026-09-02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0124_page_document_cutover")]

    operations = [
        migrations.AddField(
            model_name="workmap",
            name="collaboration_epoch",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="WorkMapBindingPlacement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("placement_id", models.UUIDField()),
                ("acknowledged_at", models.DateTimeField(null=True)),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="db.workmapbinding",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to="db.user",
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to="db.user",
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "work_map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="binding_placements",
                        to="db.workmap",
                    ),
                ),
            ],
            options={"db_table": "work_map_binding_placements"},
        ),
        migrations.CreateModel(
            name="WorkMapPasteRebinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("idempotency_key", models.UUIDField()),
                ("request_hash", models.CharField(max_length=64)),
                ("generation", models.PositiveBigIntegerField()),
                ("node_key_map", models.JSONField(default=dict)),
                ("asset_id_map", models.JSONField(default=dict)),
                ("destination_keys", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("copying", "Copying"), ("committed", "Committed"), ("failed", "Failed")],
                        default="copying",
                        max_length=10,
                    ),
                ),
                ("lease_id", models.UUIDField(null=True)),
                ("lease_expires_at", models.DateTimeField(null=True)),
                ("committed_at", models.DateTimeField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to="db.user",
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to="db.user",
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "work_map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paste_rebindings",
                        to="db.workmap",
                    ),
                ),
            ],
            options={"db_table": "work_map_paste_rebindings"},
        ),
        migrations.CreateModel(
            name="WorkMapDuplicateOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("idempotency_key", models.UUIDField()),
                ("source_generation", models.PositiveBigIntegerField()),
                ("source_scene_hash", models.CharField(max_length=64)),
                ("source_snapshot", models.JSONField(default=dict)),
                ("target_document_id", models.UUIDField()),
                ("node_key_map", models.JSONField(default=dict)),
                ("target_asset_ids", models.JSONField(default=dict)),
                ("destination_keys", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("copying", "Copying"), ("committed", "Committed"), ("failed", "Failed")],
                        default="copying",
                        max_length=10,
                    ),
                ),
                ("lease_id", models.UUIDField(null=True)),
                ("lease_expires_at", models.DateTimeField(null=True)),
                ("committed_at", models.DateTimeField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to="db.user",
                        verbose_name="Created By",
                    ),
                ),
                (
                    "source_work_map",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicate_operations",
                        to="db.workmap",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to="db.user",
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={"db_table": "work_map_duplicate_operations"},
        ),
        migrations.CreateModel(
            name="WorkMapVersion",
            fields=[
                (
                    "document_version",
                    models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="work_map",
                        serialize=False,
                        to="db.documentversion",
                    ),
                ),
                ("scene_binary", models.BinaryField(default=bytes)),
                ("binding_snapshot", models.JSONField(default=list)),
                ("generation", models.PositiveBigIntegerField()),
            ],
            options={"db_table": "work_map_versions"},
        ),
        migrations.AddConstraint(
            model_name="workmapbindingplacement",
            constraint=models.UniqueConstraint(
                fields=("work_map", "created_by", "placement_id"),
                name="work_map_binding_placement_unique_request",
            ),
        ),
        migrations.AddConstraint(
            model_name="workmappasterebinding",
            constraint=models.UniqueConstraint(
                fields=("work_map", "created_by", "idempotency_key"),
                name="work_map_paste_rebinding_unique_request",
            ),
        ),
        migrations.AddConstraint(
            model_name="workmapduplicateoperation",
            constraint=models.UniqueConstraint(
                fields=("source_work_map", "created_by", "idempotency_key"),
                name="work_map_duplicate_operation_unique_request",
            ),
        ),
    ]
