# Generated by Django 5.2.15 on 2026-09-02

import django.db.models.deletion
import uuid
from html.parser import HTMLParser

from django.conf import settings
from django.db import migrations, models


def backfill_page_asset_documents(apps, schema_editor):
    FileAsset = apps.get_model("db", "FileAsset")
    FileAsset._base_manager.filter(page_id__isnull=False, document_id__isnull=True).update(
        document_id=models.F("page_id")
    )
    if FileAsset._base_manager.filter(
        entity_type="PAGE_DESCRIPTION",
        document_id__isnull=True,
    ).exists():
        raise RuntimeError("Page description asset has no shared Document owner")


def verify_document_asset_rollback(apps, schema_editor):
    FileAsset = apps.get_model("db", "FileAsset")
    if FileAsset._base_manager.filter(entity_type="WORK_MAP_SCENE").exists():
        raise RuntimeError("Document asset rollback blocked by retained Work map scene assets")


class PageAssetReferenceParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.asset_ids = set()

    def handle_starttag(self, tag, attrs):
        if tag != "image-component":
            return
        source = dict(attrs).get("src")
        try:
            self.asset_ids.add(uuid.UUID(str(source)))
        except (TypeError, ValueError):
            return

    def handle_startendtag(self, tag, attrs):
        self.handle_starttag(tag, attrs)


def page_version_asset_ids(description_html):
    parser = PageAssetReferenceParser()
    parser.feed(description_html or "")
    return parser.asset_ids


def backfill_page_version_assets(apps, schema_editor):
    DocumentVersion = apps.get_model("db", "DocumentVersion")
    DocumentVersionAsset = apps.get_model("db", "DocumentVersionAsset")
    FileAsset = apps.get_model("db", "FileAsset")
    PageVersion = apps.get_model("db", "PageVersion")

    for page_version in PageVersion._base_manager.iterator(chunk_size=1000):
        document_id = (
            DocumentVersion._base_manager.filter(id=page_version.pk).values_list("document_id", flat=True).first()
        )
        if document_id is None:
            raise RuntimeError("Page version has no shared DocumentVersion")
        expected_ids = page_version_asset_ids(page_version.description_html)
        referenced_assets = {asset.id: asset for asset in FileAsset._base_manager.filter(id__in=expected_ids)}
        if any(
            asset.document_id != document_id or asset.entity_type != "PAGE_DESCRIPTION"
            for asset in referenced_assets.values()
        ):
            raise RuntimeError("Page version asset references are not owned by its Document")
        retained_expected_ids = set(referenced_assets)

        existing_ids = set(
            DocumentVersionAsset.objects.filter(document_version_id=page_version.pk).values_list("asset_id", flat=True)
        )
        if not existing_ids.issubset(retained_expected_ids):
            raise RuntimeError("Page version has unexpected retained asset edges")
        DocumentVersionAsset.objects.bulk_create(
            [
                DocumentVersionAsset(document_version_id=page_version.pk, asset_id=asset_id)
                for asset_id in retained_expected_ids - existing_ids
            ],
            ignore_conflicts=True,
        )
        retained_ids = set(
            DocumentVersionAsset.objects.filter(document_version_id=page_version.pk).values_list("asset_id", flat=True)
        )
        if retained_ids != retained_expected_ids:
            raise RuntimeError("Page version asset retention parity failed")


class Migration(migrations.Migration):
    dependencies = [("db", "0125_work_map_lifecycle")]

    operations = [
        migrations.AddField(
            model_name="fileasset",
            name="document",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_assets",
                to="db.document",
            ),
        ),
        migrations.RunPython(backfill_page_asset_documents, verify_document_asset_rollback),
        migrations.CreateModel(
            name="DocumentVersionAsset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="document_version_links",
                        to="db.fileasset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_links",
                        to="db.documentversion",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "document_version_assets",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document_version", "asset"),
                        name="document_version_asset_unique_edge",
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_page_version_assets, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="fileasset",
            constraint=models.CheckConstraint(
                condition=~models.Q(("entity_type__in", ["PAGE_DESCRIPTION", "WORK_MAP_SCENE"]))
                | models.Q(("document__isnull", False)),
                name="content_asset_has_document",
            ),
        ),
        migrations.AddConstraint(
            model_name="fileasset",
            constraint=models.CheckConstraint(
                condition=~models.Q(("entity_type", "WORK_MAP_SCENE"))
                | (
                    models.Q(("document__isnull", False))
                    & models.Q(("workspace__isnull", False))
                    & models.Q(("project__isnull", True))
                    & models.Q(("page__isnull", True))
                    & models.Q(("user__isnull", True))
                    & models.Q(("draft_issue__isnull", True))
                    & models.Q(("issue__isnull", True))
                    & models.Q(("comment__isnull", True))
                ),
                name="work_map_scene_asset_has_document_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="fileasset",
            constraint=models.CheckConstraint(
                condition=models.Q(("document__isnull", True))
                | models.Q(("entity_type__in", ["PAGE_DESCRIPTION", "WORK_MAP_SCENE"])),
                name="file_asset_document_owner_is_closed",
            ),
        ),
    ]
