# Generated by Django 5.2.15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0125_workspace_agent_membership"),
        ("db", "0127_work_map_asset_placement"),
    ]

    operations = []
