# Generated by Django 5.2.15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0127_message_work_item_intent"),
        ("db", "0128_merge_work_map_and_workspace_agent_membership"),
    ]

    operations = []
