/* eslint-disable no-await-in-loop -- Rasterize frames sequentially to bound encoder memory. */
import { createRequire } from "node:module";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import * as React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import sharp from "sharp";

import { SITE_NAME } from "@plane/constants";

import { CompanyRunnerLockup } from "../src/icons/brand/company-runner-lockup";
import { CompanyRunnerLogo } from "../src/icons/brand/company-runner-logo";
import { CompanyRunnerWordmark } from "../src/icons/brand/company-runner-wordmark";
import { COMPANY_RUNNER_WORDMARK_TYPOGRAPHY } from "../src/icons/brand/company-runner-wordmark";

const require = createRequire(import.meta.url);
const fontkit = require("fontkit") as {
  openSync(path: string): {
    unitsPerEm: number;
    layout(text: string): {
      glyphs: Array<{ path: { toSVG(): string }; advanceWidth: number }>;
      positions: Array<{ xAdvance: number; yAdvance: number; xOffset: number; yOffset: number }>;
    };
  };
};

const SOURCE_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");
const FONT_PATH = join(SOURCE_ROOT, COMPANY_RUNNER_WORDMARK_TYPOGRAPHY.fontFile);
const DARK = "#281D32";

const staticSvg = (element: React.ReactElement) =>
  `<?xml version="1.0" encoding="UTF-8"?>\n<!-- Generated by pnpm brand:generate; edit src/icons/brand instead. -->\n${outlineWordmark(renderToStaticMarkup(element))}\n`;

const element = (type: string, props: Record<string, unknown>, ...children: React.ReactNode[]) =>
  React.createElement(type, props, ...children);

const logo = (props: Record<string, unknown> = {}) => React.createElement(CompanyRunnerLogo, props);
const wordmark = (color: string, props: Record<string, unknown> = {}) =>
  React.createElement(CompanyRunnerWordmark, { color, ...props });

function renderMarkSvg(width = 96, height = 64) {
  return staticSvg(React.createElement(CompanyRunnerLogo, { width: String(width), height: String(height) }));
}

function renderWordmarkSvg(color: string) {
  return staticSvg(React.createElement(CompanyRunnerWordmark, { color }));
}

function renderLockupSvg(color: string) {
  return staticSvg(React.createElement(CompanyRunnerLockup, { wordmarkColor: color }));
}

function renderStackedSvg(color: string) {
  return staticSvg(
    element(
      "svg",
      { width: "224", height: "112", viewBox: "0 0 224 112", xmlns: "http://www.w3.org/2000/svg" },
      element("g", { transform: "translate(64 0)" }, logo({ width: "96", height: "64", "aria-hidden": true })),
      element("g", { transform: "translate(0 72)" }, wordmark(color, { "aria-hidden": true }))
    )
  );
}

function renderAppIconSvg(width: number, height = width) {
  const markWidth = width * 0.75;
  const markHeight = markWidth / 1.5;
  return staticSvg(
    element(
      "svg",
      {
        width: String(width),
        height: String(height),
        viewBox: `0 0 ${width} ${height}`,
        xmlns: "http://www.w3.org/2000/svg",
      },
      element("rect", { width, height, rx: width * (14 / 64), fill: DARK }),
      logo({
        width: markWidth,
        height: markHeight,
        x: (width - markWidth) / 2,
        y: (height - markHeight) / 2,
        "aria-hidden": true,
      })
    )
  );
}

function renderMarkCanvasSvg(
  width: number,
  height: number,
  { pulse, gradient = false }: { pulse?: number; gradient?: boolean } = {}
) {
  const markHeight = Math.min(height * 0.9, (width * 0.82) / 1.5);
  const markWidth = markHeight * 1.5;
  return staticSvg(
    element(
      "svg",
      {
        width: String(width),
        height: String(height),
        viewBox: `0 0 ${width} ${height}`,
        xmlns: "http://www.w3.org/2000/svg",
      },
      logo({
        width: markWidth,
        height: markHeight,
        x: (width - markWidth) / 2,
        y: (height - markHeight) / 2,
        middleOpacity: pulse,
        middleGlowOpacity: pulse === undefined ? undefined : 0.07 + 0.06 * pulse,
        gradient,
        "aria-hidden": true,
      })
    )
  );
}

function renderHorizontalSvg(color: string, width = 178, height = 40) {
  const scale = Math.min((width / 284) * 0.92, (height / 40) * 0.82);
  return staticSvg(
    element(
      "svg",
      { width, height, viewBox: `0 0 ${width} ${height}`, xmlns: "http://www.w3.org/2000/svg" },
      element(
        "g",
        { transform: `translate(${(width - 284 * scale) / 2} ${(height - 40 * scale) / 2}) scale(${scale})` },
        React.createElement(CompanyRunnerLockup, { wordmarkColor: color })
      )
    )
  );
}

function wordmarkPaths(color: string) {
  const font = fontkit.openSync(FONT_PATH);
  const run = font.layout(SITE_NAME);
  const scale = COMPANY_RUNNER_WORDMARK_TYPOGRAPHY.fontSize / font.unitsPerEm;
  let x: number = COMPANY_RUNNER_WORDMARK_TYPOGRAPHY.x;
  let y: number = COMPANY_RUNNER_WORDMARK_TYPOGRAPHY.baseline;
  const paths = run.glyphs.map((glyph, index) => {
    const position = run.positions[index]!;
    const path = element("path", {
      d: glyph.path.toSVG(),
      fill: color,
      transform: `translate(${(x + position.xOffset * scale).toFixed(4)} ${(y - position.yOffset * scale).toFixed(4)}) scale(${scale.toFixed(8)} ${(-scale).toFixed(8)})`,
    });
    x += position.xAdvance * scale;
    y -= position.yAdvance * scale;
    if (index < run.glyphs.length - 1) x += COMPANY_RUNNER_WORDMARK_TYPOGRAPHY.letterSpacing;
    return path;
  });
  return paths;
}

function outlineWordmark(svg: string) {
  // Only our own SSR wordmark is processed; no external SVG input is accepted.
  const expected = renderToStaticMarkup(React.createElement(React.Fragment, null, SITE_NAME));
  return svg.replace(/<text\b([^>]*)>([^<]*)<\/text>/g, (_, attributes: string, text: string) => {
    const color = /\bfill="([^"]+)"/.exec(attributes)?.[1];
    if (text !== expected || !color) throw new Error("Unexpected wordmark text or fill in identity source");
    return renderToStaticMarkup(element("g", {}, ...wordmarkPaths(color)));
  });
}

async function rasterSvg(svg: string, format: "png" | "webp") {
  const image = sharp(Buffer.from(svg));
  return format === "png"
    ? image.png({ compressionLevel: 9, adaptiveFiltering: false }).toBuffer()
    : image.webp({ lossless: true }).toBuffer();
}

async function animatedGif(width: number, height: number, frames: number) {
  const delays = Array.from({ length: frames }, (_, index) => (index === frames - 1 ? 180 : index % 3 === 1 ? 40 : 30));
  const rawFrames: Buffer[] = [];
  for (let index = 0; index < frames; index += 1) {
    const phase = 0.5 - 0.5 * Math.cos((2 * Math.PI * index) / (frames - 1));
    const pulse = 0.8 + 0.2 * phase;
    rawFrames.push(
      await sharp(Buffer.from(renderMarkCanvasSvg(width, height, { pulse })))
        .ensureAlpha()
        .raw()
        .toBuffer()
    );
  }
  return sharp(Buffer.concat(rawFrames), {
    raw: { width, height: height * frames, channels: 4, pageHeight: height },
  })
    .gif({ delay: delays, loop: 0, keepDuplicateFrames: true })
    .toBuffer();
}

function pngIco(images: Array<{ width: number; data: Buffer }>) {
  const header = Buffer.alloc(6);
  header.writeUInt16LE(0, 0);
  header.writeUInt16LE(1, 2);
  header.writeUInt16LE(images.length, 4);
  const entries: Buffer[] = [];
  const payload: Buffer[] = [];
  let offset = 6 + images.length * 16;
  for (const image of images) {
    const entry = Buffer.alloc(16);
    entry.writeUInt8(image.width >= 256 ? 0 : image.width, 0);
    entry.writeUInt8(image.width >= 256 ? 0 : image.width, 1);
    entry.writeUInt8(0, 2);
    entry.writeUInt8(0, 3);
    entry.writeUInt16LE(1, 4);
    entry.writeUInt16LE(32, 6);
    entry.writeUInt32LE(image.data.length, 8);
    entry.writeUInt32LE(offset, 12);
    entries.push(entry);
    payload.push(image.data);
    offset += image.data.length;
  }
  return Buffer.concat([header, ...entries, ...payload]);
}

function renderTakeoffSvg(background: string) {
  return staticSvg(
    element(
      "svg",
      {
        width: "91",
        height: "90",
        viewBox: "0 0 91 90",
        xmlns: "http://www.w3.org/2000/svg",
        role: "img",
        "aria-label": `${SITE_NAME} icon`,
      },
      element("circle", { cx: "45.5", cy: "45", r: "45", fill: background }),
      element(
        "g",
        { transform: "translate(8.19 20.126667) scale(0.777291667)" },
        logo({ width: "96", height: "64", "aria-hidden": true })
      )
    )
  );
}

function renderSpaceLogoSvg() {
  return staticSvg(
    element(
      "svg",
      {
        width: "155",
        height: "155",
        viewBox: "0 0 155 155",
        xmlns: "http://www.w3.org/2000/svg",
        role: "img",
        "aria-label": `${SITE_NAME} mark`,
      },
      element(
        "g",
        { transform: "translate(13.95 35.133333) scale(1.323958333)" },
        logo({ width: "96", height: "64", "aria-hidden": true })
      )
    )
  );
}

export {
  DARK,
  renderMarkSvg,
  renderWordmarkSvg,
  renderLockupSvg,
  renderStackedSvg,
  renderAppIconSvg,
  renderMarkCanvasSvg,
  renderHorizontalSvg,
  rasterSvg,
  animatedGif,
  pngIco,
  renderTakeoffSvg,
  renderSpaceLogoSvg,
};
